name: Snapshot

on:
  push:
    branches:
      - v5
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    env:
      CI: true
      JFROG_BUILD_STATUS: PASS
      JFROG_CLI_BUILD_NAME: ecosystem-artifactory_gradle_plugin-dev
      JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
      JFROG_CLI_BUILD_PROJECT: ecosys
    steps:
      - name: Checkout v5
        uses: actions/checkout@v4
        with:
          ref: v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "8"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle-v5-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v5-

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: Configure JFrog CLI servers
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_APIKEY: ${{ secrets.ARTIFACTORY_APIKEY }}
        run: |
          jf c rm --quiet
          jf c add internal --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_APIKEY
          jf gradlec --use-wrapper --repo-resolve ecosys-maven-remote --repo-deploy ecosys-oss-snapshot-local --deploy-maven-desc

      - name: Run audit
        run: jf audit --fail=false --exclusions "*node_modules*;*target*;*venv*;*test*;*functionalTest*"

      - name: Delete former snapshots
        run: jf rt del "ecosys-oss-snapshot-local/com/jfrog/buildinfo/build-info-extractor-gradle/*" --quiet

      - name: Build and publish snapshot
        run: jf gradle clean validatePlugins build artifactoryPublish -x test -x functionalTest

      - name: Publish build info
        run: |
          jf rt bag && jf rt bce
          jf rt bp

      - name: Distribute release bundle
        run: |
          jf ds rbc ecosystem-artifactory_gradle_plugin-snapshot ${{ github.run_number }} --spec=./.jfrog-pipelines/release/specs/dev-rbc-filespec.json --sign
          jf ds rbd ecosystem-artifactory_gradle_plugin-snapshot ${{ github.run_number }} --site="releases.jfrog.io" --sync
